# Generated by Django 4.0 on 2021-12-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinginfo',
            name='buildingName',
            field=models.CharField(default='df', max_length=250),
            preserve_default=False,
        ),
    ]
