# Generated by Django 4.0 on 2021-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_buildinginfo_buildingname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBuildingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='csvupload/')),
            ],
        ),
    ]
