# Generated by Django 4.0 on 2021-12-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_uploadbuildinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMeterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='csvupload/')),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('meterid', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fuel', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=250)),
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.buildinginfo')),
            ],
        ),
    ]
